### ISSUE TITLE
Infinite loop password prompt

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-console#7]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7560
User: @waltertamboer
Created On: 2015-05-30T08:55:03Z
Updated At: 2015-11-06T21:58:16Z
Body
The `Zend\Console\Prompt\Password` class seems to end up in an infinite loop when ran in an MINGW32 console (giti bash) on Windows machines and in the normal Windows console. (Test  on Windwos 8.1 - Zend Framework 2.4.2)

There is a `while (true)` loop which only breaks when the entered character is equal to `PHP_EOL`, this never seems to be true.

I'm not sure how this behaves on Mac or Linux machines but maybe it would be better to check for line endings:
`if (ord($char) === 10 || ord($char) === 13) {`

Issue #7559 might be related.

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-console/issues/21

**Comment by saulotoledo** [comment]
@weierophinney I played a bit with this, but I am not able to submit a full working PR right now. Here is my feedback:

- The problem is related to PowerShell. I am not sure the exact cause, but I believe newer versions have some behavior changes. `KeyAvailable` at https://github.com/laminas/laminas-console/blob/master/src/Adapter/Windows.php#L266 is never false and there is an infinite loop. I basically removed the while loop and that is working, but I could not reproduce your comment at https://github.com/laminas/laminas-console/blob/master/src/Adapter/Windows.php#L258

- After fixing the PowerShell line, we have the char 13. We need to convert it to PHP_EOL, otherwise we will be stuck at https://github.com/laminas/laminas-console/blob/master/src/Prompt/Password.php#L51

- https://github.com/laminas/laminas-console/blob/master/src/Adapter/Windows.php#L266 is also related to the uppercase characters at https://github.com/laminas/laminas-console/issues/6 (needs investigation)

**Comment by weierophinney** [comment]
> This package is **abandoned** and will receive no further development!
>
> We recommend using [laminas/laminas-cli](https://docs.laminas.dev/laminas-cli/).
